var projects = [
  {
    name     : 'Veno File Manager',
    description : 'VFM is a simple and flexible plug-and-play file manager, easy to use and plenty of options.',
    tag      : 'PHP',
    img      : '',
    url      : 'http://watsujito.sytes.net/demo/indexx.php?i=n/',
    purchase : 'https://1.envato.market/q4EOy',
    // purchase : 'http://codecanyon.net/item/veno-file-manager-host-and-share-files/6114247?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fveno-file-manager-host-and-share-files%2F6114247',
    tooltip  : 'host and share files',
    slug     : 'vfm',
  },
  {
    name     : 'QRcdr',
    description : 'Generate your personal QR Code in few clicks! Upload your logo, select custom colors, and download the final QRcode. Available formats: .png, .svg, .eps',
    tag      : 'PHP',
    img      : '',
    url      : 'https://veno.es/qrcdr/',
    purchase : 'https://1.envato.market/m5XaX',
    // purchase : 'http://codecanyon.net/item/qrcdr-responsive-qr-code-generator/9226839?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fqrcdr-responsive-qr-code-generator%2F9226839',
    tooltip  : 'responsive QR Code generator ',
    slug     : 'qrcdr',
  },
  {
    name     : 'MeMeMe',
    description : 'Easy to use and full featured WordPress plugin to quickly turn your site into a Meme portal, or to simply offer a funny tool for your users.',
    tag      : 'WP',
    img      : '',
    url      : 'https://veno.es/mememe/',
    purchase : 'https://1.envato.market/eKraj',
    // purchase : 'https://codecanyon.net/item/mememe-ultimate-meme-generator-wp-plugin/20518209?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fmememe-ultimate-meme-generator-wp-plugin%2F20518209',
    tooltip  : 'WordPress plugin',
    slug     : 'mememe',
  },
  {
    name     : 'MagiCards',
    description : 'Give your visitors a chance to know their future with a funny plugin.',
    tag      : 'WP',
    img      : '',
    url      : 'https://veno.es/magicards/',
    purchase : 'https://1.envato.market/75Gdy',
    // purchase : 'https://codecanyon.net/item/magicards-decks-of-cards-to-shuffle-wp-plugin/21572447?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fmagicards-decks-of-cards-to-shuffle-wp-plugin%2F21572447',
    tooltip  : 'WordPress plugin',
    slug     : 'magicards',
  },
  {
    name     : 'Magic Answers',
    description : 'Give your visitors a chance to know their future with a funny plugin.',
    tag      : 'WP',
    img      : '',
    url      : 'https://veno.es/magic-answers/',
    purchase : 'https://1.envato.market/5gMqL',
    // purchase : 'http://codecanyon.net/item/magic-answers-plugin/6791235?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fmagic-answers-plugin%2F6791235',
    tooltip  : 'WordPress plugin',
    slug     : 'ma',
  },
  {
    name     : 'StoCookie plugin',
    description : 'Simple and lightweight plugin to quickly create custom notification messages. Supports multilanguage with WPML and qTranslate-x',
    tag      : 'WP',
    img      : '',
    url      : 'https://veno.es/stocookie/',
    purchase : 'https://1.envato.market/vN4We',
    // purchase : 'https://codecanyon.net/item/stocookie-wp-plugin-cookie-law-compliance-and-custom-notifications/18676291?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fstocookie-wp-plugin-cookie-law-compliance-and-custom-notifications%2F18676291',
    tooltip  : 'WordPress plugin',
    slug     : 'stocookie',
  },
  {
    name     : 'StoCookie JS',
    description : 'Simple and lightweight plugin to quickly create custom notification messages. It comes with some smart options to best suit your website.',
    tag      : 'JS',
    img      : '',
    url      : 'https://veno.es/stocookie/',
    purchase : 'https://1.envato.market/Wq6gM',
    // purchase : 'https://codecanyon.net/item/stocookie-jquery-plugin-cookie-law-compliance-and-custom-notifications/18766371?ref=nicolafranchini',
    // purchase : 'https://1.envato.market/c/1287907/275988/4415?u=https%3A%2F%2Fcodecanyon.net%2Fitem%2Fstocookie-jquery-plugin-cookie-law-compliance-and-custom-notifications%2F18766371',
    tooltip  : 'jQuery plugin',
    slug     : 'stocookie-js',
  }
];